version: "2.1"

volumes:
  settings:
  ollama:
  open-webui:

services:
  ollama-service:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434

  open-webui:
    image: ghcr.io/open-webui/open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama-service
    ports:
      - "80:8080"
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama-service:11434/api"
      - "OLLAMA_BASE_URL=http://ollama-service:11434"
      # - "WEBUI_AUTH=False"
    restart: always
    privileged: true
    # network_mode: host
